### ISSUE TITLE
Add migrations

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-invite#7]
We need to add a migrations directory and put some migrations in there.

**Comment by ldko** [comment]
@damonkelley I was attempting to create migrations for invite app using Django 1.7 (initial migration on code before the AbstractInvitation came into being). It doesn't like the `def make_uuid()` being in the Invitation model that is then used in the same class to set the `activation_code` `default` value. Do you see any problem or better solution to me moving `make_uuid()` outside of the Invitation model class but leaving it in models.py?

Here is the error:

```
$ python manage.py makemigrations invite
Migrations for 'invite':
  0001_initial.py:
    - Create model Invitation
    - Create model InviteItem
    - Create model PasswordResetInvitation
    - Add field groups to invitation
    - Add field permissions to invitation
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "django-invite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "django-invite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django-invite/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "django-invite/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "django-invite/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 124, in handle
    self.write_migration_files(changes)
  File "django-invite/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 152, in write_migration_files
    migration_string = writer.as_string()
  File "django-invite/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 129, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "django-invite/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 80, in serialize
    arg_string, arg_imports = MigrationWriter.serialize(item)
  File "django-invite/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 245, in serialize
    item_string, item_imports = cls.serialize(item)
  File "django-invite/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 310, in serialize
    return cls.serialize_deconstructed(path, args, kwargs)
  File "django-invite/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 221, in serialize_deconstructed
    arg_string, arg_imports = cls.serialize(arg)
  File "django-invite/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 342, in serialize
    % (value.__name__, module_name))
ValueError: Could not find function make_uuid in invite.models.
Please note that due to Python 2 limitations, you cannot serialize unbound method functions 
(e.g. a method declared and used in the same class body). Please move the function into the
 main module body to use migrations.
```

**Comment by damonkelley** [comment]
I am guessing that is because `self` is not being passed to it. I would try adding that and see what happens.

**Comment by damonkelley** [comment]
But yeah there is no issue with moving it outside of the class. We also might be able to just attach it as a lambda to the `default` kwarg.

**Comment by ldko** [comment]
`NameError: name 'self' is not defined` when I try to pass `self` and run `makemigrations`.

**Comment by ldko** [comment]
Migrations have since been added.
